apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: exf9ojibw-python 
  janus-idp.io/tekton: exf9ojibw-python
  backstage.io/kubernetes-id: exf9ojibw-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: exf9ojibw-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml