apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: exf9ojibw-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: exf9ojibw-python 
  name: exf9ojibw-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: exf9ojibw-python 
